/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class ThemTaiKHoan extends javax.swing.JFrame {

    /**
     * Creates new form ThemTaiKHoan
     */
    public ThemTaiKHoan() {
        initComponents();
        addActionListeners();
    }
    String url = "jdbc:sqlserver://DESKTOP-HGI7VB9:1433;databaseName=QUANLYCHAMCONG;user=sa;password=thai;";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

     private void addActionListeners() {
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                kiemTraVaThemTaiKhoan();
            }
        });
    }

    private void kiemTraVaThemTaiKhoan() {
        // Lấy dữ liệu từ các ô văn bản
        String tenDangNhap = jTextField1.getText();
        String matKhau = jTextField2.getText();

        // Kiểm tra xem tài khoản có tồn tại và mật khẩu đáp ứng yêu cầu hay không
        if (kiemTraTaiKhoanTonTai(tenDangNhap)) {
            JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại. Vui lòng chọn tên đăng nhập khác.");
        }else {
            // Nếu tài khoản chưa tồn tại và mật khẩu hợp lệ, thêm mới
            themTaiKhoan(tenDangNhap, matKhau);
        }
    }

    private boolean kiemTraTaiKhoanTonTai(String tenDangNhap) {
        try (Connection conn = DriverManager.getConnection(url)) {
            String query = "SELECT * FROM TAIKHOAN WHERE TenDangNhap = ?";
            try (PreparedStatement pstmt = conn.prepareStatement(query)) {
                pstmt.setString(1, tenDangNhap);
                try (ResultSet rs = pstmt.executeQuery()) {
                    return rs.next(); // Nếu có ít nhất một bản ghi, tài khoản đã tồn tại
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            return false; // Xử lý lỗi theo ý của bạn
        }
    }

    private boolean kiemTraMatKhauHopLe(String matKhau) {
        // Thêm các điều kiện kiểm tra mật khẩu ở đây, ví dụ:
        // Mật khẩu phải có ít nhất 8 ký tự
        // Mật khẩu phải chứa ít nhất một chữ cái và một số
        return matKhau.length() >= 8 && matKhau.matches(".*[a-zA-Z].*") && matKhau.matches(".*\\d.*");
    }

    private void themTaiKhoan(String tenDangNhap, String matKhau) {
        try (Connection conn = DriverManager.getConnection(url)) {
            // Tạo một MaTK ngẫu nhiên
            String maTK = generateRandomMaTK();

            // Chèn dữ liệu vào bảng TAIKHOAN
            String insertQuery = "INSERT INTO TAIKHOAN (MaTK, TenDangNhap, MatKhau) VALUES (?, ?, ?)";
            try (PreparedStatement pstmt = conn.prepareStatement(insertQuery)) {
                pstmt.setString(1, maTK);
                pstmt.setString(2, tenDangNhap);
                pstmt.setString(3, matKhau);

                // Thực hiện câu lệnh chèn
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công!");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm tài khoản. Vui lòng kiểm tra lại!");
        }
    }

    private String generateRandomMaTK() {
        // Tạo một MaTK ngẫu nhiên sử dụng một cách tiếp cận đơn giản
        Random random = new Random();
        int randomNumber = random.nextInt(100000); // Điều chỉnh phạm vi theo nhu cầu
        return "TK" + String.format("%05d", randomNumber);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thêm Tài Khoản");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 160, 54));

        jLabel2.setText("Nhập tên đăng nhập");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 130, 40));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 180, 40));

        jLabel3.setText("Nhập mật khẩu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, 40));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 180, 40));

        jButton1.setText("Xác nhận");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 100, 30));

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TrangChu tc=new TrangChu();
        tc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemTaiKHoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemTaiKHoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemTaiKHoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemTaiKHoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemTaiKHoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
