/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

public class TinhLuongTheoNgay extends javax.swing.JFrame {

    private static final String URL = "jdbc:sqlserver://DESKTOP-HGI7VB9:1433;databaseName=QUANLYCHAMCONG";
    private static final String USER = "sa";
    private static final String PASSWORD = "thai";

    /**
     * Creates new form TinhLuongTheoNgay
     */
    public TinhLuongTheoNgay() {
        initComponents();
        loadTableData();
    }

    private void loadTableData() {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        try {
            // Kết nối đến CSDL
            connection = DriverManager.getConnection(URL, USER, PASSWORD);

            // Truy vấn dữ liệu từ các bảng và thực hiện tính toán lương
            String query = "SELECT NV.HoTen, NV.NgaySinh, BC.NgayChamCong, BC.SoGioLamTrongNgay, "
                    + "NG.TenNgay, NG.HeSoLuongNgay, CV.TenChucVu, CV.HeSoLuongChucVu, "
                    + "CASE WHEN BC.SoGioLamTrongNgay > 8 THEN (8 * 25000 * NG.HeSoLuongNgay * CV.HeSoLuongChucVu + (BC.SoGioLamTrongNgay - 8) * 25000 * 1.5 * NG.HeSoLuongNgay * CV.HeSoLuongChucVu) "
                    + "ELSE (BC.SoGioLamTrongNgay * 25000 * NG.HeSoLuongNgay * CV.HeSoLuongChucVu) END AS Luong "
                    + "FROM BANGCHAMCONG BC "
                    + "JOIN NHANVIEN NV ON BC.MaNhanVien = NV.MaNhanVien "
                    + "JOIN NGAY NG ON BC.MaNgay = NG.MaNgay "
                    + "JOIN CHUCVU CV ON NV.MaChucVu = CV.MaChucVu";
            preparedStatement = connection.prepareStatement(query);
            resultSet = preparedStatement.executeQuery();

            // Tạo DefaultTableModel cho jTable1
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Họ Tên");
            model.addColumn("Ngày Sinh");
            model.addColumn("Ngày Chấm Công");
            model.addColumn("Số Giờ Làm Trong Ngày");
            model.addColumn("Tên Ngày");
            model.addColumn("Hệ Số Lương Ngày");
            model.addColumn("Chức Vụ");
            model.addColumn("Hệ Số Lương Chức Vụ");
            model.addColumn("Lương");

            while (resultSet.next()) {
                // Lấy dữ liệu từ ResultSet
                String hoTen = resultSet.getString("HoTen");
                String ngaySinh = resultSet.getString("NgaySinh");
                String ngayChamCong = resultSet.getString("NgayChamCong");
                float soGioLamTrongNgay = resultSet.getFloat("SoGioLamTrongNgay");
                String tenNgay = resultSet.getString("TenNgay");
                float heSoLuongNgay = resultSet.getFloat("HeSoLuongNgay");
                String tenChucVu = resultSet.getString("TenChucVu");
                float heSoLuongChucVu = resultSet.getFloat("HeSoLuongChucVu");
                float luong = resultSet.getFloat("Luong");

                // Thêm dữ liệu vào model
                model.addRow(new Object[]{hoTen, ngaySinh, ngayChamCong, soGioLamTrongNgay,
                        tenNgay, heSoLuongNgay, tenChucVu, heSoLuongChucVu, luong});
            }

            // Hiển thị model trong jTable1
            jTable1.setModel(model);

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                // Đóng kết nối
                if (resultSet != null) resultSet.close();
                if (preparedStatement != null) preparedStatement.close();
                if (connection != null) connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bảng Lương Theo Ngày");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 290, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 780, -1));

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TrangChu tc= new TrangChu();
        tc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinhLuongTheoNgay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinhLuongTheoNgay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinhLuongTheoNgay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinhLuongTheoNgay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TinhLuongTheoNgay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
